-- ============================================================================
-- CHAPTER MANAGEMENT PLATFORM — COMPLETE SCHEMA REFERENCE
-- ============================================================================
-- This file is NOT a migration. It is generated output from `supabase db dump
-- --schema public --linked` and documents the full current schema for developer
-- reference. Regenerate after any schema change (see docs/DEV.md §Schema change
-- recipe).
--
-- Ground truth for TypeScript types is `lib/supabase/types.ts` (generated by
-- `npm run types:db`). If this file disagrees with types.ts, types.ts wins.
-- ============================================================================





SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."get_my_group_ids"() RETURNS SETOF "uuid"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select gm.group_id from group_memberships gm
  join status_definitions sd on sd.id = gm.status_id
  where gm.person_id = auth.uid()
    and sd.slug != 'expelled'
    and gm.ended_at is null
$$;


ALTER FUNCTION "public"."get_my_group_ids"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_my_org_ids"() RETURNS SETOF "uuid"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select get_my_group_ids()
$$;


ALTER FUNCTION "public"."get_my_org_ids"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_my_organization_ids"() RETURNS SETOF "uuid"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select om.org_id from org_memberships om
  join status_definitions sd on sd.id = om.status_id
  where om.person_id = auth.uid()
    and sd.slug != 'expelled'
    and om.ended_at is null
$$;


ALTER FUNCTION "public"."get_my_organization_ids"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."persons" (
    "id" "uuid" NOT NULL,
    "full_name" "text" NOT NULL,
    "school_email" "text" NOT NULL,
    "phone" "text",
    "personal_email" "text",
    "profile_photo" "text",
    "bio" "text",
    "nickname" "text",
    "date_of_birth" "date",
    "pledge_class_id" "uuid",
    "big_id" "uuid",
    "initiation_date" "date",
    "member_number" "text",
    "expected_grad_year" integer,
    "major" "text",
    "quickbooks_customer_id" "text",
    "quickbooks_vendor_id" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "first_name" "text",
    "middle_name" "text",
    "last_name" "text",
    "preferred_name" "text",
    "bid_date" "date",
    "street_address" "text",
    "city" "text",
    "state" "text",
    "country" "text",
    "emergency_contact_relationship" "text",
    "emergency_contact_person_id" "uuid"
);


ALTER TABLE "public"."persons" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."position_assignments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "position_id" "uuid" NOT NULL,
    "person_id" "uuid" NOT NULL,
    "group_id" "uuid" NOT NULL,
    "term_id" "uuid" NOT NULL,
    "term_start" "date",
    "term_end" "date",
    "is_acting" boolean DEFAULT false,
    "assigned_by" "uuid"
);


ALTER TABLE "public"."position_assignments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."positions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "group_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "system_role_id" "uuid",
    "type" "text",
    "permission_level" "text",
    "max_holders" integer DEFAULT 1,
    "has_budget" boolean DEFAULT false,
    "is_presiding_officer" boolean DEFAULT false,
    "semester_scope" "text"[],
    "officer_selection" "text",
    "is_locked" boolean DEFAULT false,
    "can_rename" boolean DEFAULT true,
    "display_order" integer,
    CONSTRAINT "positions_officer_selection_check" CHECK (("officer_selection" = ANY (ARRAY['elected'::"text", 'appointed'::"text", 'carried_over'::"text"]))),
    CONSTRAINT "positions_permission_level_check" CHECK (("permission_level" = ANY (ARRAY['exec'::"text", 'officer'::"text"]))),
    CONSTRAINT "positions_type_check" CHECK (("type" = ANY (ARRAY['exec'::"text", 'committee'::"text", 'house'::"text", 'board'::"text", 'other'::"text"])))
);


ALTER TABLE "public"."positions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."system_position_roles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "slug" "text" NOT NULL,
    "default_name" "text" NOT NULL,
    "description" "text",
    "is_presiding_officer" boolean DEFAULT false,
    "is_treasurer" boolean DEFAULT false,
    "is_secretary" boolean DEFAULT false,
    "is_vice_president" boolean DEFAULT false,
    "is_house_manager" boolean DEFAULT false,
    "is_rush_chair" boolean DEFAULT false,
    "is_required" boolean DEFAULT false
);


ALTER TABLE "public"."system_position_roles" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."current_system_role_holders" AS
 SELECT "pa"."group_id" AS "org_id",
    "spr"."slug" AS "system_role",
    "pa"."person_id",
    "p"."full_name",
    "pos"."title" AS "position_title"
   FROM ((("public"."position_assignments" "pa"
     JOIN "public"."positions" "pos" ON (("pos"."id" = "pa"."position_id")))
     JOIN "public"."system_position_roles" "spr" ON (("spr"."id" = "pos"."system_role_id")))
     JOIN "public"."persons" "p" ON (("p"."id" = "pa"."person_id")))
  WHERE ("pa"."term_end" IS NULL);


ALTER VIEW "public"."current_system_role_holders" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."event_categories" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "group_id" "uuid",
    "name" "text" NOT NULL,
    "color" "text",
    "icon" "text"
);


ALTER TABLE "public"."event_categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."facilities" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "organization_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "address" "text",
    "managed_by_group_id" "uuid"
);


ALTER TABLE "public"."facilities" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."group_memberships" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "person_id" "uuid" NOT NULL,
    "group_id" "uuid" NOT NULL,
    "chapter_email" "text",
    "joined_at" "date",
    "notes" "text",
    "role_type_id" "uuid",
    "status_id" "uuid",
    "started_at" "date" DEFAULT CURRENT_DATE,
    "ended_at" "date"
);


ALTER TABLE "public"."group_memberships" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."group_relationships" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "parent_group_id" "uuid" NOT NULL,
    "child_group_id" "uuid" NOT NULL,
    "relationship_type_id" "uuid" NOT NULL,
    "status" "text" DEFAULT 'active'::"text",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "group_relationships_check" CHECK (("parent_group_id" <> "child_group_id")),
    CONSTRAINT "group_relationships_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'active'::"text", 'rejected'::"text"])))
);


ALTER TABLE "public"."group_relationships" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."groups" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "organization_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "group_type" "text",
    "features" "jsonb" DEFAULT '{}'::"jsonb",
    "settings" "jsonb" DEFAULT '{}'::"jsonb",
    "terminology" "jsonb" DEFAULT '{}'::"jsonb",
    "is_primary" boolean DEFAULT false,
    "logo_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."groups" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."national_org_templates" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "parent_organization_id" "uuid" NOT NULL,
    "chapter_type" "text" NOT NULL,
    "display_name" "text" NOT NULL,
    "default_features" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "term_structure" "text",
    "is_default" boolean DEFAULT false
);


ALTER TABLE "public"."national_org_templates" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."org_relationship_types" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "slug" "text" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "default_permissions" "jsonb" DEFAULT '{"can_view_events": false, "can_view_housing": false, "can_view_members": false, "can_view_documents": false, "can_view_financials": false, "can_view_leadership": true, "can_view_roster_count": true}'::"jsonb" NOT NULL
);


ALTER TABLE "public"."org_relationship_types" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."organization_admins" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "organization_id" "uuid" NOT NULL,
    "person_id" "uuid" NOT NULL,
    "granted_by" "uuid",
    "granted_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."organization_admins" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."organizations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "org_type" "text" NOT NULL,
    "features" "jsonb" DEFAULT '{}'::"jsonb",
    "settings" "jsonb" DEFAULT '{}'::"jsonb",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "parent_organization_id" "uuid",
    "logo_url" "text",
    "terminology" "jsonb" DEFAULT '{}'::"jsonb"
);


ALTER TABLE "public"."organizations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."parent_organizations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "abbreviation" "text",
    "org_type" "text" NOT NULL,
    "founded_year" integer,
    "website" "text",
    "logo_url" "text",
    "status" "text" DEFAULT 'active'::"text",
    "submitted_by" "uuid",
    "approved_by" "uuid",
    "slug" "text" NOT NULL,
    CONSTRAINT "national_organizations_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'pending'::"text", 'inactive'::"text"])))
);


ALTER TABLE "public"."parent_organizations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."platform_admins" (
    "id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."platform_admins" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pledge_classes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "group_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "term_id" "uuid",
    "initiated_count" integer DEFAULT 0
);


ALTER TABLE "public"."pledge_classes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."role_types" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "group_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "description" "text",
    "is_default" boolean DEFAULT false,
    "access_level" "text" NOT NULL,
    "can_vote" boolean DEFAULT false,
    "can_hold_office" boolean DEFAULT false,
    "can_attend_events" boolean DEFAULT true,
    "can_view_roster" boolean DEFAULT true,
    "can_view_financials" boolean DEFAULT false,
    "can_submit_expenses" boolean DEFAULT false,
    "can_view_minutes" boolean DEFAULT true,
    "can_speak_at_meetings" boolean DEFAULT true,
    "can_view_documents" boolean DEFAULT true,
    "color" "text",
    "display_order" integer,
    CONSTRAINT "affiliation_types_access_level_check" CHECK (("access_level" = ANY (ARRAY['full'::"text", 'limited'::"text", 'read_only'::"text", 'none'::"text"])))
);


ALTER TABLE "public"."role_types" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."room_assignments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "room_id" "uuid" NOT NULL,
    "member_id" "uuid" NOT NULL,
    "term_id" "uuid" NOT NULL,
    "starts_on" "date" NOT NULL,
    "ends_on" "date",
    "notes" "text"
);


ALTER TABLE "public"."room_assignments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."rooms" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "facility_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "type" "text",
    "floor" "text",
    "capacity" integer DEFAULT 1,
    "is_active" boolean DEFAULT true,
    "display_order" integer,
    "nickname" "text",
    "room_number" "text",
    "square_footage" integer,
    "floor_plan_code" "text",
    "floor_plan_use" "text",
    "description" "text",
    "beds" integer DEFAULT 0,
    "mattresses" integer DEFAULT 0,
    "dressers" integer DEFAULT 0,
    "desks" integer DEFAULT 0,
    "desk_chairs" integer DEFAULT 0,
    "book_shelves" integer DEFAULT 0,
    "closets" integer DEFAULT 0,
    "sofas" integer DEFAULT 0,
    "loft_kits" integer DEFAULT 0,
    "ideal_capacity" integer,
    CONSTRAINT "rooms_type_check" CHECK (("type" = ANY (ARRAY['single'::"text", 'double'::"text", 'common'::"text", 'bathroom'::"text", 'storage'::"text", 'study'::"text", 'lounge'::"text", 'service'::"text", 'other'::"text"])))
);


ALTER TABLE "public"."rooms" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."status_definitions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "group_id" "uuid",
    "name" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "description" "text",
    "is_base" boolean DEFAULT false,
    "override_access_level" "text",
    "override_can_vote" boolean,
    "override_can_hold_office" boolean,
    "override_can_attend_events" boolean,
    "override_can_view_roster" boolean,
    "override_can_view_financials" boolean,
    "override_can_submit_expenses" boolean,
    "override_can_view_minutes" boolean,
    "override_can_speak_at_meetings" boolean,
    "override_can_view_documents" boolean,
    "color" "text",
    "display_order" integer,
    CONSTRAINT "status_definitions_override_access_level_check" CHECK (("override_access_level" = ANY (ARRAY['full'::"text", 'limited'::"text", 'read_only'::"text", 'none'::"text"])))
);


ALTER TABLE "public"."status_definitions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."subgroup_members" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "subgroup_id" "uuid" NOT NULL,
    "person_id" "uuid" NOT NULL,
    "role" "text" DEFAULT 'member'::"text",
    "join_type" "text",
    "appointed_by" "uuid",
    "joined_at" "date" DEFAULT CURRENT_DATE,
    "left_at" "date",
    CONSTRAINT "subgroup_members_join_type_check" CHECK (("join_type" = ANY (ARRAY['appointed'::"text", 'elected'::"text", 'self_joined'::"text", 'invited'::"text", 'automatic'::"text"]))),
    CONSTRAINT "subgroup_members_role_check" CHECK (("role" = ANY (ARRAY['head'::"text", 'member'::"text"])))
);


ALTER TABLE "public"."subgroup_members" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."subgroups" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "group_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "subgroup_type" "text",
    "membership_type" "text",
    "head_position_id" "uuid",
    "pledge_class_id" "uuid",
    "is_private" boolean DEFAULT false,
    "is_locked" boolean DEFAULT false,
    "can_rename" boolean DEFAULT true,
    CONSTRAINT "subgroups_membership_type_check" CHECK (("membership_type" = ANY (ARRAY['appointed'::"text", 'elected'::"text", 'open'::"text", 'invite_only'::"text", 'automatic'::"text"]))),
    CONSTRAINT "subgroups_subgroup_type_check" CHECK (("subgroup_type" = ANY (ARRAY['committee'::"text", 'exec_board'::"text", 'pledge_class'::"text", 'house_residents'::"text", 'ad_hoc'::"text", 'family_line'::"text", 'advisory_board'::"text"])))
);


ALTER TABLE "public"."subgroups" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."term_definitions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "group_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "ordinal" integer NOT NULL,
    "start_month" integer NOT NULL,
    "start_day" integer NOT NULL,
    "end_month" integer NOT NULL,
    "end_day" integer NOT NULL,
    "has_elections" boolean DEFAULT true,
    "has_budget" boolean DEFAULT true,
    "has_rollover" boolean DEFAULT true,
    "has_rush" boolean DEFAULT false,
    "officer_selection" "text" DEFAULT 'elected'::"text",
    "auto_generate" boolean DEFAULT true,
    "generate_months_ahead" integer DEFAULT 2,
    "is_active" boolean DEFAULT true,
    CONSTRAINT "term_definitions_officer_selection_check" CHECK (("officer_selection" = ANY (ARRAY['elected'::"text", 'appointed'::"text", 'carried_over'::"text"])))
);


ALTER TABLE "public"."term_definitions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."terms" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "group_id" "uuid" NOT NULL,
    "definition_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "year" integer NOT NULL,
    "starts_on" "date" NOT NULL,
    "ends_on" "date" NOT NULL,
    "status" "text" DEFAULT 'upcoming'::"text",
    "has_elections" boolean NOT NULL,
    "has_budget" boolean NOT NULL,
    "has_rollover" boolean NOT NULL,
    "has_rush" boolean NOT NULL,
    "officer_selection" "text" NOT NULL,
    CONSTRAINT "terms_status_check" CHECK (("status" = ANY (ARRAY['upcoming'::"text", 'active'::"text", 'completed'::"text"])))
);


ALTER TABLE "public"."terms" OWNER TO "postgres";


ALTER TABLE ONLY "public"."role_types"
    ADD CONSTRAINT "affiliation_types_org_id_slug_key" UNIQUE ("group_id", "slug");



ALTER TABLE ONLY "public"."role_types"
    ADD CONSTRAINT "affiliation_types_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."event_categories"
    ADD CONSTRAINT "event_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."group_relationships"
    ADD CONSTRAINT "group_relationships_parent_group_id_child_group_id_relation_key" UNIQUE ("parent_group_id", "child_group_id", "relationship_type_id");



ALTER TABLE ONLY "public"."group_relationships"
    ADD CONSTRAINT "group_relationships_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."groups"
    ADD CONSTRAINT "groups_organization_id_slug_key" UNIQUE ("organization_id", "slug");



ALTER TABLE ONLY "public"."groups"
    ADD CONSTRAINT "groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."facilities"
    ADD CONSTRAINT "house_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."national_org_templates"
    ADD CONSTRAINT "national_org_templates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."parent_organizations"
    ADD CONSTRAINT "national_organizations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."group_memberships"
    ADD CONSTRAINT "org_memberships_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."org_relationship_types"
    ADD CONSTRAINT "org_relationship_types_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."org_relationship_types"
    ADD CONSTRAINT "org_relationship_types_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."organization_admins"
    ADD CONSTRAINT "organization_admins_organization_id_person_id_key" UNIQUE ("organization_id", "person_id");



ALTER TABLE ONLY "public"."organization_admins"
    ADD CONSTRAINT "organization_admins_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "orgs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."persons"
    ADD CONSTRAINT "persons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."platform_admins"
    ADD CONSTRAINT "platform_admins_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pledge_classes"
    ADD CONSTRAINT "pledge_classes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."position_assignments"
    ADD CONSTRAINT "position_assignments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."positions"
    ADD CONSTRAINT "positions_org_id_slug_key" UNIQUE ("group_id", "slug");



ALTER TABLE ONLY "public"."positions"
    ADD CONSTRAINT "positions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."room_assignments"
    ADD CONSTRAINT "room_assignments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."room_assignments"
    ADD CONSTRAINT "room_assignments_room_id_member_id_term_id_key" UNIQUE ("room_id", "member_id", "term_id");



ALTER TABLE ONLY "public"."rooms"
    ADD CONSTRAINT "rooms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."status_definitions"
    ADD CONSTRAINT "status_definitions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subgroup_members"
    ADD CONSTRAINT "subgroup_members_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subgroup_members"
    ADD CONSTRAINT "subgroup_members_subgroup_id_person_id_key" UNIQUE ("subgroup_id", "person_id");



ALTER TABLE ONLY "public"."subgroups"
    ADD CONSTRAINT "subgroups_org_id_slug_key" UNIQUE ("group_id", "slug");



ALTER TABLE ONLY "public"."subgroups"
    ADD CONSTRAINT "subgroups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."system_position_roles"
    ADD CONSTRAINT "system_position_roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."system_position_roles"
    ADD CONSTRAINT "system_position_roles_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."term_definitions"
    ADD CONSTRAINT "term_definitions_org_id_slug_key" UNIQUE ("group_id", "slug");



ALTER TABLE ONLY "public"."term_definitions"
    ADD CONSTRAINT "term_definitions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."terms"
    ADD CONSTRAINT "terms_org_id_definition_id_year_key" UNIQUE ("group_id", "definition_id", "year");



ALTER TABLE ONLY "public"."terms"
    ADD CONSTRAINT "terms_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "org_memberships_active_role_idx" ON "public"."group_memberships" USING "btree" ("person_id", "group_id", "role_type_id") WHERE ("ended_at" IS NULL);



CREATE UNIQUE INDEX "organizations_slug_idx" ON "public"."organizations" USING "btree" ("slug");



CREATE UNIQUE INDEX "parent_organizations_slug_idx" ON "public"."parent_organizations" USING "btree" ("slug");



CREATE UNIQUE INDEX "status_definitions_org_slug_idx" ON "public"."status_definitions" USING "btree" (COALESCE("group_id", '00000000-0000-0000-0000-000000000000'::"uuid"), "slug");



ALTER TABLE ONLY "public"."facilities"
    ADD CONSTRAINT "facilities_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."group_memberships"
    ADD CONSTRAINT "group_memberships_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id");



ALTER TABLE ONLY "public"."group_relationships"
    ADD CONSTRAINT "group_relationships_child_group_id_fkey" FOREIGN KEY ("child_group_id") REFERENCES "public"."groups"("id");



ALTER TABLE ONLY "public"."group_relationships"
    ADD CONSTRAINT "group_relationships_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."group_relationships"
    ADD CONSTRAINT "group_relationships_parent_group_id_fkey" FOREIGN KEY ("parent_group_id") REFERENCES "public"."groups"("id");



ALTER TABLE ONLY "public"."group_relationships"
    ADD CONSTRAINT "group_relationships_relationship_type_id_fkey" FOREIGN KEY ("relationship_type_id") REFERENCES "public"."org_relationship_types"("id");



ALTER TABLE ONLY "public"."groups"
    ADD CONSTRAINT "groups_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."national_org_templates"
    ADD CONSTRAINT "national_org_templates_national_org_id_fkey" FOREIGN KEY ("parent_organization_id") REFERENCES "public"."parent_organizations"("id");



ALTER TABLE ONLY "public"."parent_organizations"
    ADD CONSTRAINT "national_organizations_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."parent_organizations"
    ADD CONSTRAINT "national_organizations_submitted_by_fkey" FOREIGN KEY ("submitted_by") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."group_memberships"
    ADD CONSTRAINT "org_memberships_affiliation_type_id_fkey" FOREIGN KEY ("role_type_id") REFERENCES "public"."role_types"("id");



ALTER TABLE ONLY "public"."group_memberships"
    ADD CONSTRAINT "org_memberships_person_id_fkey" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."group_memberships"
    ADD CONSTRAINT "org_memberships_status_id_fkey" FOREIGN KEY ("status_id") REFERENCES "public"."status_definitions"("id");



ALTER TABLE ONLY "public"."organization_admins"
    ADD CONSTRAINT "organization_admins_granted_by_fkey" FOREIGN KEY ("granted_by") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."organization_admins"
    ADD CONSTRAINT "organization_admins_org_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."organization_admins"
    ADD CONSTRAINT "organization_admins_person_id_fkey" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "orgs_parent_organization_id_fkey" FOREIGN KEY ("parent_organization_id") REFERENCES "public"."parent_organizations"("id");



ALTER TABLE ONLY "public"."persons"
    ADD CONSTRAINT "persons_big_id_fkey" FOREIGN KEY ("big_id") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."persons"
    ADD CONSTRAINT "persons_emergency_contact_person_id_fkey" FOREIGN KEY ("emergency_contact_person_id") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."persons"
    ADD CONSTRAINT "persons_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."persons"
    ADD CONSTRAINT "persons_pledge_class_id_fkey" FOREIGN KEY ("pledge_class_id") REFERENCES "public"."pledge_classes"("id");



ALTER TABLE ONLY "public"."platform_admins"
    ADD CONSTRAINT "platform_admins_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."pledge_classes"
    ADD CONSTRAINT "pledge_classes_term_id_fkey" FOREIGN KEY ("term_id") REFERENCES "public"."terms"("id");



ALTER TABLE ONLY "public"."position_assignments"
    ADD CONSTRAINT "position_assignments_assigned_by_fkey" FOREIGN KEY ("assigned_by") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."position_assignments"
    ADD CONSTRAINT "position_assignments_person_id_fkey" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."position_assignments"
    ADD CONSTRAINT "position_assignments_position_id_fkey" FOREIGN KEY ("position_id") REFERENCES "public"."positions"("id");



ALTER TABLE ONLY "public"."position_assignments"
    ADD CONSTRAINT "position_assignments_term_id_fkey" FOREIGN KEY ("term_id") REFERENCES "public"."terms"("id");



ALTER TABLE ONLY "public"."positions"
    ADD CONSTRAINT "positions_system_role_id_fkey" FOREIGN KEY ("system_role_id") REFERENCES "public"."system_position_roles"("id");



ALTER TABLE ONLY "public"."room_assignments"
    ADD CONSTRAINT "room_assignments_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."room_assignments"
    ADD CONSTRAINT "room_assignments_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id");



ALTER TABLE ONLY "public"."room_assignments"
    ADD CONSTRAINT "room_assignments_term_id_fkey" FOREIGN KEY ("term_id") REFERENCES "public"."terms"("id");



ALTER TABLE ONLY "public"."rooms"
    ADD CONSTRAINT "rooms_facility_id_fkey" FOREIGN KEY ("facility_id") REFERENCES "public"."facilities"("id");



ALTER TABLE ONLY "public"."subgroup_members"
    ADD CONSTRAINT "subgroup_members_appointed_by_fkey" FOREIGN KEY ("appointed_by") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."subgroup_members"
    ADD CONSTRAINT "subgroup_members_person_id_fkey" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id");



ALTER TABLE ONLY "public"."subgroup_members"
    ADD CONSTRAINT "subgroup_members_subgroup_id_fkey" FOREIGN KEY ("subgroup_id") REFERENCES "public"."subgroups"("id");



ALTER TABLE ONLY "public"."subgroups"
    ADD CONSTRAINT "subgroups_head_position_id_fkey" FOREIGN KEY ("head_position_id") REFERENCES "public"."positions"("id");



ALTER TABLE ONLY "public"."subgroups"
    ADD CONSTRAINT "subgroups_pledge_class_id_fkey" FOREIGN KEY ("pledge_class_id") REFERENCES "public"."pledge_classes"("id");



ALTER TABLE ONLY "public"."terms"
    ADD CONSTRAINT "terms_definition_id_fkey" FOREIGN KEY ("definition_id") REFERENCES "public"."term_definitions"("id");



ALTER TABLE "public"."event_categories" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "event_categories_select" ON "public"."event_categories" FOR SELECT USING ((("group_id" IS NULL) OR ("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids"))));



ALTER TABLE "public"."facilities" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "facilities_select" ON "public"."facilities" FOR SELECT USING (("organization_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



ALTER TABLE "public"."group_memberships" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."group_relationships" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "group_relationships_delete" ON "public"."group_relationships" FOR DELETE USING ((("parent_group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")) OR ("child_group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids"))));



CREATE POLICY "group_relationships_insert" ON "public"."group_relationships" FOR INSERT WITH CHECK ((("parent_group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")) OR ("child_group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids"))));



CREATE POLICY "group_relationships_select" ON "public"."group_relationships" FOR SELECT USING ((("parent_group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")) OR ("child_group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids"))));



CREATE POLICY "group_relationships_update" ON "public"."group_relationships" FOR UPDATE USING ((("parent_group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")) OR ("child_group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids"))));



ALTER TABLE "public"."groups" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "groups_delete" ON "public"."groups" FOR DELETE USING ((("organization_id" IN ( SELECT "organization_admins"."organization_id"
   FROM "public"."organization_admins"
  WHERE ("organization_admins"."person_id" = "auth"."uid"()))) OR (EXISTS ( SELECT 1
   FROM "public"."platform_admins"
  WHERE ("platform_admins"."id" = "auth"."uid"())))));



CREATE POLICY "groups_insert" ON "public"."groups" FOR INSERT WITH CHECK (("organization_id" IN ( SELECT "organization_admins"."organization_id"
   FROM "public"."organization_admins"
  WHERE ("organization_admins"."person_id" = ( SELECT "auth"."uid"() AS "uid")))));



CREATE POLICY "groups_select" ON "public"."groups" FOR SELECT USING (("id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



CREATE POLICY "groups_update" ON "public"."groups" FOR UPDATE USING (("organization_id" IN ( SELECT "organization_admins"."organization_id"
   FROM "public"."organization_admins"
  WHERE ("organization_admins"."person_id" = ( SELECT "auth"."uid"() AS "uid")))));



ALTER TABLE "public"."national_org_templates" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "org_memberships_insert" ON "public"."group_memberships" FOR INSERT WITH CHECK (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "org_memberships_select" ON "public"."group_memberships" FOR SELECT USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "org_memberships_update" ON "public"."group_memberships" FOR UPDATE USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids"))) WITH CHECK (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



ALTER TABLE "public"."org_relationship_types" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "org_relationship_types_admin_all" ON "public"."org_relationship_types" USING ((EXISTS ( SELECT 1
   FROM "public"."platform_admins"
  WHERE ("platform_admins"."id" = ( SELECT "auth"."uid"() AS "uid")))));



CREATE POLICY "org_relationship_types_select" ON "public"."org_relationship_types" FOR SELECT USING (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."organization_admins" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "organization_admins_delete" ON "public"."organization_admins" FOR DELETE USING ((("organization_id" IN ( SELECT "organization_admins_1"."organization_id"
   FROM "public"."organization_admins" "organization_admins_1"
  WHERE ("organization_admins_1"."person_id" = ( SELECT "auth"."uid"() AS "uid")))) OR (EXISTS ( SELECT 1
   FROM "public"."platform_admins"
  WHERE ("platform_admins"."id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "organization_admins_insert" ON "public"."organization_admins" FOR INSERT WITH CHECK ((("organization_id" IN ( SELECT "organization_admins_1"."organization_id"
   FROM "public"."organization_admins" "organization_admins_1"
  WHERE ("organization_admins_1"."person_id" = ( SELECT "auth"."uid"() AS "uid")))) OR (EXISTS ( SELECT 1
   FROM "public"."platform_admins"
  WHERE ("platform_admins"."id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "organization_admins_select" ON "public"."organization_admins" FOR SELECT USING (("organization_id" IN ( SELECT "g"."organization_id"
   FROM "public"."groups" "g"
  WHERE ("g"."id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")))));



CREATE POLICY "organization_admins_update" ON "public"."organization_admins" FOR UPDATE USING ((("organization_id" IN ( SELECT "organization_admins_1"."organization_id"
   FROM "public"."organization_admins" "organization_admins_1"
  WHERE ("organization_admins_1"."person_id" = "auth"."uid"()))) OR (EXISTS ( SELECT 1
   FROM "public"."platform_admins"
  WHERE ("platform_admins"."id" = "auth"."uid"())))));



ALTER TABLE "public"."organizations" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "organizations_admin_all" ON "public"."organizations" USING ((EXISTS ( SELECT 1
   FROM "public"."platform_admins"
  WHERE ("platform_admins"."id" = ( SELECT "auth"."uid"() AS "uid")))));



CREATE POLICY "organizations_select" ON "public"."organizations" FOR SELECT USING ((("id" IN ( SELECT "g"."organization_id"
   FROM "public"."groups" "g"
  WHERE ("g"."id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")))) OR (EXISTS ( SELECT 1
   FROM "public"."platform_admins"
  WHERE ("platform_admins"."id" = ( SELECT "auth"."uid"() AS "uid"))))));



CREATE POLICY "parent_org_templates_select" ON "public"."national_org_templates" FOR SELECT USING (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."parent_organizations" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "parent_organizations_select" ON "public"."parent_organizations" FOR SELECT USING (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."persons" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "persons_select" ON "public"."persons" FOR SELECT USING ((("id" IN ( SELECT "gm2"."person_id"
   FROM ("public"."group_memberships" "gm1"
     JOIN "public"."group_memberships" "gm2" ON (("gm2"."group_id" = "gm1"."group_id")))
  WHERE (("gm1"."person_id" = ( SELECT "auth"."uid"() AS "uid")) AND ("gm1"."ended_at" IS NULL)))) OR ("id" = ( SELECT "auth"."uid"() AS "uid"))));



CREATE POLICY "persons_update" ON "public"."persons" FOR UPDATE USING (("id" = ( SELECT "auth"."uid"() AS "uid")));



ALTER TABLE "public"."platform_admins" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pledge_classes" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "pledge_classes_select" ON "public"."pledge_classes" FOR SELECT USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



ALTER TABLE "public"."position_assignments" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "position_assignments_select" ON "public"."position_assignments" FOR SELECT USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



ALTER TABLE "public"."positions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "positions_delete" ON "public"."positions" FOR DELETE USING (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



CREATE POLICY "positions_insert" ON "public"."positions" FOR INSERT WITH CHECK (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



CREATE POLICY "positions_select" ON "public"."positions" FOR SELECT USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "positions_update" ON "public"."positions" FOR UPDATE USING (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



ALTER TABLE "public"."role_types" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "role_types_delete" ON "public"."role_types" FOR DELETE USING (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



CREATE POLICY "role_types_insert" ON "public"."role_types" FOR INSERT WITH CHECK (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "role_types_select" ON "public"."role_types" FOR SELECT USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "role_types_update" ON "public"."role_types" FOR UPDATE USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



ALTER TABLE "public"."room_assignments" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "room_assignments_select" ON "public"."room_assignments" FOR SELECT USING (("room_id" IN ( SELECT "r"."id"
   FROM ("public"."rooms" "r"
     JOIN "public"."facilities" "f" ON (("f"."id" = "r"."facility_id")))
  WHERE ("f"."organization_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")))));



ALTER TABLE "public"."rooms" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "rooms_select" ON "public"."rooms" FOR SELECT USING (("facility_id" IN ( SELECT "facilities"."id"
   FROM "public"."facilities"
  WHERE ("facilities"."organization_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")))));



ALTER TABLE "public"."status_definitions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "status_definitions_delete" ON "public"."status_definitions" FOR DELETE USING (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



CREATE POLICY "status_definitions_insert" ON "public"."status_definitions" FOR INSERT WITH CHECK (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "status_definitions_select" ON "public"."status_definitions" FOR SELECT USING ((("group_id" IS NULL) OR ("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids"))));



CREATE POLICY "status_definitions_update" ON "public"."status_definitions" FOR UPDATE USING (((("group_id" IS NULL) AND (EXISTS ( SELECT 1
   FROM "public"."platform_admins"
  WHERE ("platform_admins"."id" = ( SELECT "auth"."uid"() AS "uid"))))) OR ("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids"))));



ALTER TABLE "public"."subgroup_members" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "subgroup_members_insert" ON "public"."subgroup_members" FOR INSERT WITH CHECK (("subgroup_id" IN ( SELECT "subgroups"."id"
   FROM "public"."subgroups"
  WHERE ("subgroups"."group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")))));



CREATE POLICY "subgroup_members_select" ON "public"."subgroup_members" FOR SELECT USING (("subgroup_id" IN ( SELECT "subgroups"."id"
   FROM "public"."subgroups"
  WHERE ("subgroups"."group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")))));



CREATE POLICY "subgroup_members_update" ON "public"."subgroup_members" FOR UPDATE USING (("subgroup_id" IN ( SELECT "subgroups"."id"
   FROM "public"."subgroups"
  WHERE ("subgroups"."group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")))));



ALTER TABLE "public"."subgroups" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "subgroups_delete" ON "public"."subgroups" FOR DELETE USING ((("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")) AND (NOT "is_locked")));



CREATE POLICY "subgroups_insert" ON "public"."subgroups" FOR INSERT WITH CHECK (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "subgroups_select" ON "public"."subgroups" FOR SELECT USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "subgroups_update" ON "public"."subgroups" FOR UPDATE USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



ALTER TABLE "public"."system_position_roles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "system_position_roles_select" ON "public"."system_position_roles" FOR SELECT USING (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."term_definitions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "term_definitions_delete" ON "public"."term_definitions" FOR DELETE USING (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



CREATE POLICY "term_definitions_insert" ON "public"."term_definitions" FOR INSERT WITH CHECK (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



CREATE POLICY "term_definitions_select" ON "public"."term_definitions" FOR SELECT USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "term_definitions_update" ON "public"."term_definitions" FOR UPDATE USING (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



ALTER TABLE "public"."terms" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "terms_delete" ON "public"."terms" FOR DELETE USING (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



CREATE POLICY "terms_insert" ON "public"."terms" FOR INSERT WITH CHECK (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



CREATE POLICY "terms_select" ON "public"."terms" FOR SELECT USING (("group_id" IN ( SELECT "public"."get_my_org_ids"() AS "get_my_org_ids")));



CREATE POLICY "terms_update" ON "public"."terms" FOR UPDATE USING (("group_id" IN ( SELECT "public"."get_my_group_ids"() AS "get_my_group_ids")));



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."get_my_group_ids"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_my_group_ids"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_my_group_ids"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_my_org_ids"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_my_org_ids"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_my_org_ids"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_my_organization_ids"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_my_organization_ids"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_my_organization_ids"() TO "service_role";



GRANT ALL ON TABLE "public"."persons" TO "anon";
GRANT ALL ON TABLE "public"."persons" TO "authenticated";
GRANT ALL ON TABLE "public"."persons" TO "service_role";



GRANT ALL ON TABLE "public"."position_assignments" TO "anon";
GRANT ALL ON TABLE "public"."position_assignments" TO "authenticated";
GRANT ALL ON TABLE "public"."position_assignments" TO "service_role";



GRANT ALL ON TABLE "public"."positions" TO "anon";
GRANT ALL ON TABLE "public"."positions" TO "authenticated";
GRANT ALL ON TABLE "public"."positions" TO "service_role";



GRANT ALL ON TABLE "public"."system_position_roles" TO "anon";
GRANT ALL ON TABLE "public"."system_position_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."system_position_roles" TO "service_role";



GRANT ALL ON TABLE "public"."current_system_role_holders" TO "anon";
GRANT ALL ON TABLE "public"."current_system_role_holders" TO "authenticated";
GRANT ALL ON TABLE "public"."current_system_role_holders" TO "service_role";



GRANT ALL ON TABLE "public"."event_categories" TO "anon";
GRANT ALL ON TABLE "public"."event_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."event_categories" TO "service_role";



GRANT ALL ON TABLE "public"."facilities" TO "anon";
GRANT ALL ON TABLE "public"."facilities" TO "authenticated";
GRANT ALL ON TABLE "public"."facilities" TO "service_role";



GRANT ALL ON TABLE "public"."group_memberships" TO "anon";
GRANT ALL ON TABLE "public"."group_memberships" TO "authenticated";
GRANT ALL ON TABLE "public"."group_memberships" TO "service_role";



GRANT ALL ON TABLE "public"."group_relationships" TO "anon";
GRANT ALL ON TABLE "public"."group_relationships" TO "authenticated";
GRANT ALL ON TABLE "public"."group_relationships" TO "service_role";



GRANT ALL ON TABLE "public"."groups" TO "anon";
GRANT ALL ON TABLE "public"."groups" TO "authenticated";
GRANT ALL ON TABLE "public"."groups" TO "service_role";



GRANT ALL ON TABLE "public"."national_org_templates" TO "anon";
GRANT ALL ON TABLE "public"."national_org_templates" TO "authenticated";
GRANT ALL ON TABLE "public"."national_org_templates" TO "service_role";



GRANT ALL ON TABLE "public"."org_relationship_types" TO "anon";
GRANT ALL ON TABLE "public"."org_relationship_types" TO "authenticated";
GRANT ALL ON TABLE "public"."org_relationship_types" TO "service_role";



GRANT ALL ON TABLE "public"."organization_admins" TO "anon";
GRANT ALL ON TABLE "public"."organization_admins" TO "authenticated";
GRANT ALL ON TABLE "public"."organization_admins" TO "service_role";



GRANT ALL ON TABLE "public"."organizations" TO "anon";
GRANT ALL ON TABLE "public"."organizations" TO "authenticated";
GRANT ALL ON TABLE "public"."organizations" TO "service_role";



GRANT ALL ON TABLE "public"."parent_organizations" TO "anon";
GRANT ALL ON TABLE "public"."parent_organizations" TO "authenticated";
GRANT ALL ON TABLE "public"."parent_organizations" TO "service_role";



GRANT ALL ON TABLE "public"."platform_admins" TO "anon";
GRANT ALL ON TABLE "public"."platform_admins" TO "authenticated";
GRANT ALL ON TABLE "public"."platform_admins" TO "service_role";



GRANT ALL ON TABLE "public"."pledge_classes" TO "anon";
GRANT ALL ON TABLE "public"."pledge_classes" TO "authenticated";
GRANT ALL ON TABLE "public"."pledge_classes" TO "service_role";



GRANT ALL ON TABLE "public"."role_types" TO "anon";
GRANT ALL ON TABLE "public"."role_types" TO "authenticated";
GRANT ALL ON TABLE "public"."role_types" TO "service_role";



GRANT ALL ON TABLE "public"."room_assignments" TO "anon";
GRANT ALL ON TABLE "public"."room_assignments" TO "authenticated";
GRANT ALL ON TABLE "public"."room_assignments" TO "service_role";



GRANT ALL ON TABLE "public"."rooms" TO "anon";
GRANT ALL ON TABLE "public"."rooms" TO "authenticated";
GRANT ALL ON TABLE "public"."rooms" TO "service_role";



GRANT ALL ON TABLE "public"."status_definitions" TO "anon";
GRANT ALL ON TABLE "public"."status_definitions" TO "authenticated";
GRANT ALL ON TABLE "public"."status_definitions" TO "service_role";



GRANT ALL ON TABLE "public"."subgroup_members" TO "anon";
GRANT ALL ON TABLE "public"."subgroup_members" TO "authenticated";
GRANT ALL ON TABLE "public"."subgroup_members" TO "service_role";



GRANT ALL ON TABLE "public"."subgroups" TO "anon";
GRANT ALL ON TABLE "public"."subgroups" TO "authenticated";
GRANT ALL ON TABLE "public"."subgroups" TO "service_role";



GRANT ALL ON TABLE "public"."term_definitions" TO "anon";
GRANT ALL ON TABLE "public"."term_definitions" TO "authenticated";
GRANT ALL ON TABLE "public"."term_definitions" TO "service_role";



GRANT ALL ON TABLE "public"."terms" TO "anon";
GRANT ALL ON TABLE "public"."terms" TO "authenticated";
GRANT ALL ON TABLE "public"."terms" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







