-- Set Sigma Nu logo as an inline SVG data URI
UPDATE parent_organizations
SET logo_url = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48cmVjdCB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgcng9IjEyIiBmaWxsPSIjMDAwMDAwIi8+PHJlY3QgeD0iMTUiIHk9IjI2IiB3aWR0aD0iNzAiIGhlaWdodD0iMiIgZmlsbD0iI0M0QTc0NyIgcng9IjEiLz48dGV4dCB4PSI1MCIgeT0iNjAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJzZXJpZiIgZm9udC1zaXplPSIzNiIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiNDNEE3NDciPs6jTjwvdGV4dD48cmVjdCB4PSIxNSIgeT0iNzIiIHdpZHRoPSI3MCIgaGVpZ2h0PSIyIiBmaWxsPSIjQzRBNzQ3IiByeD0iMSIvPjwvc3ZnPg=='
WHERE slug = 'sigma-nu';
